name: fluxui
description: "Flux UI is a Flutter library for creating user interfaces that are declarative and reactive."
# Remove below line if you wish to publish to pub.dev
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Poppins-Light
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf

    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: Poppins-Black
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
